ALTER TABLE `note_types` MODIFY COLUMN `types`
    ENUM('WORD_EXPLANATION', 'LITERARY','HISTORICAL','DICTUM','CRITIQUE',
    'TITLE','TRANSLATION','REFERENCE')  CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL;

ALTER TABLE `note` MODIFY COLUMN `status`
    ENUM('INITIAL','DRAFT', 'FINISHED')  CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL;
